routes/web.php
<?php

use App\Http\Controllers\Admin\IndexController;
use App\Http\Controllers\Admin\TestController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Client\HomeController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])
    ->name('home');
Route::get('/notifications', [HomeController::class, 'notifications'])
    ->name('notifications');
Route::get('/login', [LoginController::class, 'login'])
    ->name('login.form');
Route::post('/login', [LoginController::class, 'postLogin'])
    ->name('login.post');
Route::get('/logout', [LogoutController::class, 'logout'])->name('logout');

Route::get('/course', function () {
    return view('course');
});

Route::get('/dashboard', [IndexController::class, 'index'])
    ->name('dashboard')->middleware('myweb.auth:dashboard');

Route::prefix('admin')->group(function () {
    require 'question.php';
    require 'class.php';
    require 'student.php';
    require 'course.php';
    require 'test.php';
    require 'score.php';

    require 'users.php';
    require 'roles.php';
    require 'teacher.php';
});

Route::post('/getQuestion', [TestController::class, 'getQuestion'])->name('getquestion');

app/Http/Controllers/Client/CourseDetailController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\ClassStudy;
use App\Models\Course;
use App\Models\File;
use App\Models\Lesson;
use App\Models\Unit;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Http\Request;

class CourseDetailController extends Controller
{
    /**
     * @param string $slug
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function courseDetail($slug)
    {
        $courses_slide = Course::select([
            'title',
            'slug',
            'image',
        ])->take(4)->get();

        $course = Course::where('slug', $slug)->with(['classStudies', 'users', 'units' => function ($q) {
            return $q->withCount('lessons');
        }])->first();

        $courseLesson = 0;
        foreach ($course->units as $unit) {
            $courseLesson += $unit->lessons_count;
        }

        $user = Sentinel::getUser();
        $id = $user->id;

        if ($course) {
            $units = Unit::where('course_id', $course->id)->get();
            $class_of_user = '';

            if ($user) {
                $access = $user->hasCourse($course->id);
                $class_of_user = ClassStudy::select(['class_studies.id'])
                    ->join('class_study_users AS cu', 'cu.class_study_id', 'class_studies.id')
                    ->join('class_study_courses as cc', 'cc.class_study_id', 'class_studies.id')
                    ->where('cu.user_id', $user->id)
                    ->where('cc.course_id', $course->id)
                    ->pluck('id')
                    ->toArray();
            }
            $lessons = Lesson::select([
                'ul.status',
                'unit_id',
                'lessons.title',
                'lessons.slug'
            ])
                ->leftJoin('user_lessons AS ul', 'ul.lesson_id', 'lessons.id')
                ->Join('units AS u', 'u.id', 'lessons.unit_id')
                ->where('u.course_id', $course->id)
                ->where('ul.user_id', $id)
                ->get();
            $countLesson = $lessons->where('status', 1)->count();
            $progress = 0;
            if ($countLesson != 0) {
                $progress = ceil(($countLesson * 100) / $courseLesson);
            }
            return view('client.modules.course_detail', compact(['courses_slide', 'course', 'units', 'user', 'access', 'class_of_user', 'progress', 'lessons', 'countLesson', 'courseLesson']));
        } else {
            return abort(404);
        }
    }

    /**
     * @param Request $request
     * @return \Illuminate\Routing\Redirector|\Illuminate\Http\RedirectResponse
     */
    public function attach(Request $request)
    {
        if ($user = Sentinel::getUser()) {
            $user->courses()->attach($request->course_id);
            $user->lessons()->attach($request->lesson_id);
            return redirect(route('detail', $request->course_slug))
                ->with('message', "Đăng kí khóa học thành công. Hãy học ngay !")
                ->with('type_alert', "success");
        } else {
            return redirect(route('detail', $request->course_slug))
                ->with('message', "Không thể đăng kí. Hãy đăng nhập !")
                ->with('type_alert', "success");
        }
    }

    /**
     * @param Request $request
     * @return \Illuminate\Routing\Redirector|\Illuminate\Http\RedirectResponse
     */
    public function detach(Request $request)
    {
        $user = Sentinel::getUser();
        $user->courses()->detach($request->course_id);
        $lessons = Lesson::leftJoin('user_lessons AS ul', 'ul.lesson_id', 'lessons.id')
            ->leftJoin('units AS u', 'u.id', 'lessons.unit_id')
            ->join('courses AS c', 'c.id', 'u.course_id')
            ->where('ul.user_id', $user->id)
            ->where('c.id', $request->course_id)
            ->pluck('ul.lesson_id')->all();

        $user->lessons()->detach($lessons);

        return redirect(route('detail', $request->course_slug))
            ->with('message', "Bạn đã hủy đăng kí khóa học này !")
            ->with('type_alert', "success");
    }

    /**
     * @param Request $request
     * @return \Illuminate\Routing\Redirector|\Illuminate\Http\RedirectResponse
     */
    public function attachClass(Request $request)
    {
        $user = Sentinel::getUser();
        $class = ClassStudy::where('id', $request->class_id)->first();
        $class->users()->attach($user->id);
        $user->courses()->attach($request->course_id);
        $user->lessons()->attach($request->lesson_id);
        return redirect(route('detail', $request->course_slug))
            ->with('message', "Bạn đã đăng kí lớp thành công !")
            ->with('type_alert', "success");
    }

    /**
     * @param Request $request
     * @return \Illuminate\Routing\Redirector|\Illuminate\Http\RedirectResponse
     */
    public function detachClass(Request $request)
    {
        $user = Sentinel::getUser();
        $class = ClassStudy::where('id', $request->class_id)->first();
        $class->users()->detach($user->id);
        return redirect(route('detail', $request->course_slug))
            ->with('message', "Bạn đã hủy đăng kí lớp thành công !")
            ->with('type_alert', "success");
    }

    /**
     * showLesson
     *
     * @param  mixed $id
     * @return \Illuminate\View\View
     */
    public function showLesson($id)
    {
        $lesson = Lesson::find($id);

        if ($lesson) {
            $courseId = $lesson->unit->course_id;
            $course = Course::find($courseId);
            $nextLesson = Lesson::where('id', '>', $lesson->id)
                ->where('unit_id', $lesson->unit_id)
                ->first();
            $nextUnit = Unit::where('id', '>', $lesson->unit_id)
                ->where('course_id', $courseId)
                ->with('lessons')
                ->first();
            $files = File::where('lesson_id', $id)->get();
            return view('client.modules.learning', compact('lesson', 'files', 'course', 'nextLesson', 'nextUnit'));
        } else {
            return abort(404);
        }
    }

    /**
     * @param Request $request
     * @param string $slug
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function personalLesson(Request $request, $slug)
    {
        $getUser = Sentinel::getUser();
        $lesson = Lesson::where('slug', $slug)
            ->with('unit')
            ->first();

        $userLesson = $getUser->lessons()
            ->where('lesson_id', $lesson->id)
            ->first()
            ->pivot;

        $courseId = $lesson->unit->course_id;
        $course = Course::find($courseId);
        $nextLesson = Lesson::where('id', '>', $lesson->id)
            ->where('unit_id', $lesson->unit_id)
            ->first();
        $nextUnit = Unit::where('id', '>', $lesson->unit_id)
            ->where('course_id', $courseId)
            ->with('lessons')
            ->first();
        $files = File::where('lesson_id', $lesson->id)
            ->get();

        return view('client.modules.lesson', compact('lesson', 'nextLesson', 'nextUnit', 'files', 'userLesson', 'course'));
    }

    /**
     * @param string $slug
     * @return NULL
     */
    public function lessonProgress($slug)
    {
        $getUser    = Sentinel::getUser();
        $lesson     = Lesson::where('slug', $slug)->first();
        $getUser->lessons()
            ->updateExistingPivot($lesson->id, [
                'status' => 1,
            ]);
    }
}

app/Http/Controllers/Client/HomeController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Course;
use App\Models\User;
use Illuminate\Http\Request;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class HomeController extends Controller
{
    /**
     *  @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function index()
    {
        $courses = Course::select([
            'id',
            'title',
            'slug',
            'description',
            'image'

        ])->withCount('users')
            ->orderBy('created_at', 'DESC')
            ->take(4)
            ->get();
        return view('client.modules.home', compact('courses'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function courses(Request $request)
    {
        if ($request->sort == 'old') {
            $name = 'created_at';
            $sort = 'ASC';
        } elseif ($request->sort == 'new') {
            $name = 'created_at';
            $sort = 'DESC';
        } elseif ($request->sort == 'name') {
            $name = 'title';
            $sort = 'ASC';
        } else {
            $name = 'created_at';
            $sort = 'DESC';
        }

        $courses = Course::select([
            'id',
            'title',
            'slug',
            'description',
            'image'
        ])
            ->withCount(['units', 'users'])
            ->orderBy($name, $sort)
            ->paginate(6);

        return view('client.modules.courses', compact('courses'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function courseFilter(Request $request)
    {
        $filter = '';
        if ($request->filter == 'free') {
            $filter = '0';
        } elseif ($request->filter == 'pro') {
            $filter = '1';
        }

        $query = Course::select([
            'id',
            'title',
            'slug',
            'description',
            'image'
        ])
            ->withCount(['units', 'users']);
        if ('' != $filter) {
            $query = $query->where('status', $filter);
        }
        $courses = $query->paginate(6);

        return view('client.modules.courses', compact('courses'));
    }


    /**
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function profile()
    {
        $getUser    = Sentinel::getUser();
        $id         = $getUser->id;
        $user       = User::withCount(['courses', 'lessons' => function ($query) {
            return $query->where('status', 1);
        }])->find($id);

        return view('client.modules.profile', compact('user'));
    }


    /**
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function contact()
    {
        return view('client.modules.contact');
    }

    /**
     *
     * @param Request $request
     * @return \Illuminate\Routing\Redirector|\Illuminate\Http\RedirectResponse
     */
    public function uploadImg(Request $request)
    {
        $user = User::find($request['student_id']);

        if ($request->hasFile('name_img')) {
            $file_image = $request->file('name_img');
            $user = $this->uploadFile($user, $file_image);
            $user->save();
        }
        return redirect(route('profile'));
    }

    /**
     *
     * @param integer $id
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function profileUpdate()
    {
        $getUser    = Sentinel::getUser();
        $id         = $getUser->id;
        $user       = User::find($id);
        return view('client.modules.profileUpdate', compact('user'));
    }

    /**
     *
     * @param Request $request
     * @param integer $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function saveProfileUpdates(Request $request, $id)
    {
        $student = User::find($id);
        if ($student) {
            $student->phone         = $request->input('phone');
            $student->first_name    = $request->input('first_name');
            $student->last_name     = $request->input('last_name');
            $student->gender        = $request->input('gender');
            $student->address       = $request->input('address');
            $student->birthday      = $request->input('birthday');
            if ($request->hasFile('name_img')) {
                $file_image = $request->file('name_img');
                $student    = $this->uploadFile($student, $file_image);
            }
            $student->save();
        }
        return redirect()->route('profile');
    }

    /**
     *
     * @param User $user
     * @param File $file
     * @return User
     */
    private function uploadFile($user, $file)
    {
        $oldPath    = $user->path;
        $name       = $file->getClientOriginalName();
        $newPath    = $file->storeAs('images', $name);

        if ($oldPath != NULL) {
            Storage::delete("$oldPath");
        }
        $user->name_img = $name;
        $user->path     = $newPath;
        return $user;
    }
}

app/Http/Controllers/Client/LessonProgressController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Lesson;
use App\Models\User;
use Illuminate\Http\Request;

class LessonProgressController extends Controller
{
    /**
     * @param Request $request
     * @return string
     */
    public function lessonProgress(Request $request){
        Lesson::where('id', 3)
        ->update(['title' => "abc"]);
        return 'Success! ajax in laravel 5';
    }
}

app/Http/Controllers/Client/SearchController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Course;
use Illuminate\Http\Request;

class SearchController extends Controller
{
    //
    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function search( Request $request){
        $data = Course::where('title','like', '%' .$request->keyword . '%')
            ->orWhere('description', 'like', '%' .$request->keyword . '%')
            ->withCount(['units', 'users'])
            ->paginate(6);
        return view('client.modules.search_result', compact('data'));
    }
}

resources/views/client/modules/contact.blade.php
@extends('client.layouts.master')
@section('title', 'Gửi liên hệ')

@section('content')
<div class="site-breadcrumb" style="background: url({{ asset('/user/img/breadcrumb/breadcrumb.jpg') }})">
    <div class="breadcrumb-circle">
        <img src="{{ asset('/user/img/header/header-shape-2.png') }}" class="hero-circle-1" alt="thumb">
    </div>
    <div class="container">
        <h2 class="breadcrumb-title">Liên hệ</h2>
        <ul class="breadcrumb-menu clearfix">
            <li><a href="{{ route('home') }}">Trang chủ</a></li>
            <li class="active">Tôi</li>
        </ul>
    </div>
</div>
<div class="cta-area cta-3  de-padding" id="contact">
    <div class="container">
        <div class="row">
            <div class="col-xl-8 offset-xl-2">
                <div data-text="" class="site-title text-center">
                    <span class="sub-2">Có gì mới</span>
                    <h2>Bạn có câu hỏi? Hãy liên lạc với chúng tôi</h2>
                </div>
            </div>
        </div>
        <div class="cta-wrapper grid-2">
            <div class="cta-left" style="background: url({{ asset('/user/img/footer/contact-left-bg.png') }})">
                <h2>Giải đáp mọi thắc mắc</h2>
                <div class="cta-left-wrap">
                    <div class="cta-left-single">
                        <i class="fas fa-map-marker-alt"></i>
                        <div class="cta-left-single-txt">
                            <h5>Trụ sở chính</h5>
                            <span>Tòa nhà 3D, Số 3 Duy Tân, Quận Cầu Giấy, Hà Nội</span>
                        </div>
                    </div>
                    <div class="cta-left-single">
                        <i class="fas fa-phone-volume"></i>
                        <div class="cta-left-single-txt">
                            <h5>Số điện thoại</h5>
                            <span>(+84) 24 6297 3538</span>
                        </div>
                    </div>
                    <div class="cta-left-single">
                        <i class="fas fa-envelope"></i>
                        <div class="cta-left-single-txt">
                            <h5>Email</h5>
                            <span>info@co-well.vn</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cta-right">
                <div class="contact-inputs">
                    <form class="contact-form" method="post"
                        action="https://siteforest.tech/templatebucket/lasson/assets/mail/contact.php">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="name">Họ và tên</label>
                                    <input type="text" class="form-control" name="name" id="name">
                                    <span class="alert alert-error"></span>
                                </div>
                                <div class="form-group">
                                    <label for="email">Địa chỉ email</label>
                                    <input type="email" class="form-control" name="email" id="email">
                                    <span class="alert alert-error"></span>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="comments">Khác</label>
                                    <textarea class="form-control" id="comments" name="comments" rows="5"></textarea>
                                </div>
                                <button type="submit" name="submit" id="submit">
                                    Gửi tin nhắn
                                </button>
                                <div class="alert-notification">
                                    <div id="message" class="alert-msg"></div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/client/modules/courses.blade.php
@extends('client.layouts.master')
@section('title', 'Danh sách khóa học')
@section('content')
<div class="site-breadcrumb" style="background: url({{ asset('/user/img/breadcrumb/breadcrumb.jpg') }})">
    <div class="breadcrumb-circle">
        <img src="{{ asset('/user/img/header/header-shape-2.png') }}" class="hero-circle-1" alt="thumb">
    </div>
    <div class="container">
        <h2 class="breadcrumb-title">Danh sách khóa học</h2>
        <ul class="breadcrumb-menu clearfix">
            <li><a href="{{ route('home') }}">Trang chủ</a></li>
            <li class="active">Khóa học</li>
        </ul>
    </div>
</div>

<div id="portfolio" class="portfolio-area course-2 de-padding">
    <div class="wavesshape">
        <img src="{{ asset('/user/img/course/course-bg-2.png') }}" alt="thumb">
    </div>
    <div class="container">
        <div class="row csf align-items-center">
            <div class="col-xl-8">
                <div class="site-title-left">
                    <h2>Các khóa học tuyệt vời của chúng tôi</h2>
                </div>
            </div>
            <div class="col-xl-4">
                <div class="site-title-right">
                    <h2>Course</h2>
                </div>
            </div>
        </div>
        <div class="portfolio-items-area">
            <div class="row">
                <div class="col-xl-12 portfolio-content">
                    <div class="row align-items-center">
                        <div class="col-xl-6">
                            Sắp xếp theo:
                            <a href="{{ route('courses') }}?sort=new" class="btn btn-info" style="font-size: 13px">Mới nhất</a>
                            <a href="{{ route('courses') }}?sort=old" class="btn btn-info" style="font-size: 13px">Cũ nhất</a>
                            <a href="{{ route('courses') }}?sort=name" class="btn btn-info" style="font-size: 13px">Tên A-Z</a>


                        </div>
                        <div class="col-xl-2">
                            <select name="" onchange="location = this.value;" class="form-control-lg">
                                <option value="{{ route('courses') }}">Loại khóa học</option>
                                <option value="{{ route('courses') }}"> Tất cả</option>
                                <option value="{{ route('courses.filter') }}?filter=free&" >Miễn phí</option>
                                <option value="{{ route('courses.filter') }}?filter=pro" >Trả phi</option>
                            </select>

                        </div>
                        <div class="col-xl-4">
                            <div class="course-view-more">
                                <h6>Tổng khóa học: {{ $courses->total() }} - <a>View All</a></h6>
                            </div>
                        </div>
                    </div>
                    <div class="magnific-mix-gallery masonary">
                        <div id="portfolio-grid" class="portfolio-items" style="position: relative; height: 1285.32px;">

                            @foreach ($courses as $course)
                                <div class="pf-item video photography" style="position: absolute; left: 0%; top: 0px;">
                                    <div class="course-2-box">
                                        <div class="course-2-pic">
                                            <img src="{{ asset($course->image) }}" class="course-img" alt="thumb">
                                            <div class="course-2-pic-content">
                                                <p><span>{{ $course->users_count }}</span> người đã học</p>
                                            </div>
                                        </div>
                                        <div class="course-2-content">
                                            <div class="course-2-text">
                                                <h5>{{ $course->title }}</h5>
                                                <div class="desciption_course">
                                                    {!! $course->description !!}
                                                </div>
                                            </div>
                                            <div class="course-2-bottom">
                                                <div class="course-2-lesson">
                                                    <i class="fas fa-book-open"></i>
                                                    <p class="mb-0">Tổng số chương: {{ $course->units_count }}
                                                    </p>
                                                </div>
                                            </div>
                                            <div class="course-2-btn">
                                                <a href="{{ route('detail', $course->slug) }}"
                                                    class="theme-btn btn-2">Vào khóa học</a>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            @endforeach

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="text-center">
        {{ $courses->withQueryString()->links() }}
    </div>
</div>
@endsection

resources/views/client/modules/search_result.blade.php
@extends('client.layouts.master')
@section('title', 'Kết quả tìm kiếm')

@section('content')

    <div class="site-breadcrumb" style="background: url({{ asset('/user/img/breadcrumb/breadcrumb.jpg') }})">
        <div class="breadcrumb-circle">
            <img src="{{ asset('/user/img/header/header-shape-2.png') }}" class="hero-circle-1" alt="thumb">
        </div>
        <div class="container">
            <h2 class="breadcrumb-title">Danh sách khóa học</h2>
            <ul class="breadcrumb-menu clearfix">
                <li><a href="{{ route('home') }}">Trang chủ</a></li>
                <li class="active">Khóa học</li>
            </ul>
        </div>
    </div>

    <div id="portfolio" class="portfolio-area course-2 de-padding">
        <div class="wavesshape">
            <img src="{{ asset('/user/img/course/course-bg-2.png') }}" alt="thumb">
        </div>
        <div class="container">
            <div class="row csf align-items-center">
                <div class="col-xl-8">
                    <div class="site-title-left">
                        <h2>Kết quả tìm kiếm</h2>
                    </div>
                </div>
                <div class="col-xl-4">
                    <div class="site-title-right">
                        <h2>Course</h2>
                    </div>
                </div>
            </div>
            <div class="portfolio-items-area">
                <div class="row">
                    <div class="col-xl-12 portfolio-content">
                        <div class="row align-items-center">

                            <div class="col-xl-4">
                                <div class="course-view-more">
                                    <h6>Tìm thấy {{$data->total()}} khóa học phù hợp</h6>
                                </div>
                            </div>
                        </div>
                        <div class="magnific-mix-gallery masonary">
                            <div id="portfolio-grid" class="portfolio-items" style="position: relative; height: 1285.32px;">
                                @foreach ($data as $course)
                                    <div class="pf-item video photography" style="position: absolute; left: 0%; top: 0px;">
                                        <div class="course-2-box">
                                            <div class="course-2-pic">
                                                <img src="{{ asset('/user/img/course/course-1.jpg') }}" class="course-img"
                                                    alt="thumb">
                                                <div class="course-2-pic-content">

                                                    <p><span>{{ $course->users_count }}</span> người đã học</p>
                                                </div>
                                            </div>
                                            <div class="course-2-content">

                                                <div class="course-2-text">
                                                    <h5>{{ $course->title }}</h5>
                                                    <p class="desciption_course">
                                                        {!! $course->description !!}
                                                    </p>
                                                </div>
                                                <div class="course-2-bottom">
                                                    <div class="course-2-lesson">
                                                        <i class="fas fa-book-open"></i>
                                                        <p class="mb-0">Tổng số chương: {{$course->units_count }}</p></p>
                                                    </div>
                                                </div>
                                                <div class="course-2-btn">
                                                    <a href="{{ route('detail', $course->slug) }}"
                                                        class="theme-btn btn-2">vào khóa học</a>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center">
            {{ $data->withQueryString()->links() }}
        </div>
    </div>
@endsection